import "./globals.css";
import "./media.css";
import "../styles/global.css";
import "bootstrap/dist/css/bootstrap.css";
import AddBootstrap from "./addbootstrap/AddBootstrap";
import BackToTop from "./components/BackToTop";
import CallButton from "./components/CallButton";

export const metadata = {
  title: "Cynergy Studio",
  description: "Generated by next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AddBootstrap />
        {children}
        <BackToTop />
        <CallButton />
      </body>
    </html>
  );
}
