import React from "react";
import Header from "../components/Header";
import Footer from "../components/Footer";
import InnerCta from "../components/InnerCta";

const page = () => {
  return (
    <>
      <Header />
      {/* Main Banner */}
      <div className="about-banner">
        <div className="container">
          <div className="row">
            <div className="col-md-12">
              <h1>Privacy Policy</h1>
            </div>
          </div>
          <hr />
        </div>
      </div>

      <div className="background-terms">
        <div className="container pt-0 pb-5 ">
          <div className="row">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">Definitions and key terms</h2>
              <ul>
                To help explain things as clearly as possible in this Privacy
                Policy, every time any of these terms are referenced, are
                strictly defined as:
                <li>
                  Cookie: a small amount of data generated by a website and
                  saved by your web browser. It is used to identify your
                  browser, provide analytics, and remember information about
                  you, such as your language preference or login information.
                </li>
                <li>
                  Company: When this policy mentions “Company,” “we,” “us,” or
                  “our,” it refers to Cynergy Studios (1 E Erie St Ste 525
                  Chicago, IL 60611 ), which is responsible for your information
                  under this Privacy Policy.
                </li>
                <li>
                  Country: where Cynergy Studios or the owners/founders of
                  Cynergy Studios are based, in this case, is United States
                </li>
                <li>
                  Customer refers to the company, organization, or person that
                  signs up to use the Cynergy Studios Service to manage the
                  relationships with your consumers or service users.
                </li>
                <li>
                  Device: any internet-connected device such as a phone, tablet,
                  computer, or any other device that can be used to visit
                  Cynergy Studios and use the services.
                </li>
                <li>
                  IP address: Every device connected to the Internet is assigned
                  a number known as an Internet protocol (IP) address. These
                  numbers are usually assigned in geographic blocks. An IP
                  address can often be used to identify the location from which
                  a device is connecting to the Internet.
                </li>
                <li>
                  Personnel refers to those individuals who are employed by
                  Cynergy Studios or are under contract to perform a service on
                  behalf of one of the parties.
                </li>
                <li>
                  Personal Data: any information that directly, indirectly, or
                  in connection with other information — including a personal
                  identification number — allows for the identification or
                  identifiability of a natural person.
                </li>
                <li>
                  Service refers to the service provided by Cynergy Studios as
                  described in the relative terms (if available) and on this
                  platform.
                </li>
                <li>
                  Third-party service refers to advertisers, contest sponsors,
                  promotional and marketing partners, and others who provide our
                  content or whose products or services we think may interest
                  you.
                </li>
                <li>
                  You: a person or entity that is registered with Cynergy
                  Studios to use the Services.
                </li>
              </ul>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">What Information Do We Collect?</h2>
              <ul>
                We collect information from you when you visit our website,
                register on our site, place an order, subscribe to our
                newsletter, respond to a survey, or fill out a form.
                <li>Name / Username</li>
                <li>Phone Numbers</li>
                <li>Email Addresses</li>
                <li>Mailing Addresses</li>
              </ul>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">
                When does Cynergy Studios use end-user information from third
                parties?
              </h2>
              <p>
                Cynergy Studios will collect End User Data necessary to provide
                the Cynergy Studios services to our customers. End users may
                voluntarily provide us with information they have made available
                on social media websites. If you provide us with any such
                information, we may collect publicly available information from
                the social media websites you have indicated. You can control
                how much of your information social media websites make public
                by visiting these websites and changing your privacy settings.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">
                When does Cynergy Studios use customer information from third
                parties?
              </h2>
              <p>
                We receive some information from third parties when you contact
                us. For example, when you submit your email address to us to
                show interest in becoming a Cynergy Studios customer, we receive
                information from a third party that provides automated fraud
                detection services to Cynergy Studios. We also occasionally
                collect information that is made publicly available on social
                media websites. You can control how much of your information
                social media websites make public by visiting these websites and
                changing your privacy settings.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">
                Do we share the information we collect with third parties?
              </h2>
              <p>
                We may share the information that we collect, both personal and
                non-personal, with third parties such as advertisers, contest
                sponsors, promotional and marketing partners, and others who
                provide our content or whose products or services we think may
                interest you. We may also share it with our current and future
                affiliated companies and business partners, and if we are
                involved in a merger, asset sale or other business
                reorganization, we may also share or transfer your personal and
                non-personal information to our successors-in-interest.
                <br />
                <br />
                We may engage trusted third-party service providers to perform
                functions and provide services to us, such as hosting and
                maintaining our servers and the website, database storage and
                management, e-mail management, storage marketing, credit card
                processing, customer service, and fulfilling orders for products
                and services you may purchase through the website. We will
                likely share your personal information, and possibly some
                non-personal information, with these third parties to enable
                them to perform these services for pages 3/8 us and for you.
                <br />
                <br />
                We may share portions of our log file data, including IP
                addresses, for analytics purposes with third parties such as web
                analytics partners, application developers, and ad networks. If
                your IP address is shared, it may be used to estimate general
                location and other technographics such as connection speed,
                whether you have visited the website in a shared location, and
                the type of device used to visit the website. They may aggregate
                information about our advertising and what you see on the
                website and then provide auditing, research, and reporting for
                us and our advertisers.
                <br />
                <br />
                We may also disclose personal and non-personal information about
                you to government or law enforcement officials or private
                parties as we, in our sole discretion, believe necessary or
                appropriate in order to respond to claims, legal process
                (including subpoenas), to protect our rights and interests or
                those of a third party, the safety of the public or any person,
                to prevent or stop any illegal, unethical, or legally actionable
                activity, or to otherwise comply with applicable court orders,
                laws, rules and regulations.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">
                How Do We Use The Information We Collect?
              </h2>
              <ul>
                Any of the information we collect from you may be used in one of
                the following ways:
                <li>
                  To personalize your experience (your information helps us to
                  better respond to your individual needs)
                </li>
                <li>
                  To improve our website (we continually strive to improve our
                  website offerings based on the information and feedback we
                  receive from you)
                </li>
                <li>
                  To improve customer service (your information helps us to
                  respond to your customer service requests and support needs
                  more effectively)
                </li>
                <li>To process transactions</li>
                <li>
                  To administer a contest, promotion, survey, or other site
                  feature
                </li>
                <li>To send periodic emails</li>
              </ul>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">
                How Do We Use Your Email Address?
              </h2>
              <p>
                By submitting your email address on this website, you agree to
                receive emails from us. You can cancel your participation in any
                of these email lists at any time by clicking on the opt-out link
                or other unsubscribe options that are included in the respective
                email. We only send emails to people who have authorized us to
                contact them, either directly or through a third party. We do
                not send unsolicited commercial emails because we hate spam as
                much as you do. By submitting your email address, you also agree
                to allow us to use your email address for customer audience
                targeting on sites like Facebook, where we display custom
                advertising to specific people who have opted-in to receive
                communications from us. Email addresses submitted only through
                the order processing page will be used for the sole purpose of
                sending you information and updates pertaining to your order.
                If, however, you have provided the same email to us through
                another method, we may use it for any of the purposes stated in
                this Policy. Note: If at any time you would like to unsubscribe
                page 4/8 from receiving future emails, we include detailed
                unsubscribe instructions at the bottom of each email.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">
                How Long Do We Keep Your Information?
              </h2>
              <p>
                We keep your information only so long as we need it to provide
                Cynergy Studios to you and fulfill the purposes described in
                this policy. This is also the case for anyone that we share your
                information with and who carries out services on our behalf.
                When we no longer need to use your information, and there is no
                need for us to keep it to comply with our legal or regulatory
                obligations, we’ll either remove it from our systems or
                depersonalize it so that we can&apos;t identify you.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">
                How Do We Protect Your Information?
              </h2>
              <p>
                We implement a variety of security measures to maintain the
                safety of your personal information when you place an order or
                enter, submit, or access your personal information. We offer the
                use of a secure server. All supplied sensitive/credit
                information is transmitted via Secure Socket Layer (SSL)
                technology and then encrypted into our Payment gateway providers
                database only to be accessible by those authorized with special
                access rights to such systems and are required to keep the
                information confidential. After a transaction, your private
                information (credit cards, social security numbers, financials,
                etc.) is never kept on file. We cannot, however, ensure or
                warrant the absolute security of any information you transmit to
                Cynergy Studios or guarantee that your information on the
                Service may not be accessed, disclosed, altered, or destroyed by
                a breach of any of our physical, technical, or managerial
                safeguards.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">
                Could my information be transferred to other countries?
              </h2>
              <p>
                Cynergy Studios is incorporated in the United States.
                Information collected via our website, through direct
                interactions with you, or from the use of our help services may
                be transferred from time to time to our offices or personnel or
                third parties located throughout the world. It may be viewed and
                hosted anywhere in the world, including countries that may not
                have laws of general applicability regulating the use and
                transfer of such data. To the fullest extent allowed by
                applicable law, by using any of the above, you voluntarily
                consent to the trans-border transfer and hosting of such
                information.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">
                Is the information collected through the Cynergy Studios Service
                secure?
              </h2>
              <p>
                We take precautions to protect the security of your information.
                We have physical, electronic, and managerial procedures to help
                safeguard, prevent unauthorized access, maintain data security,
                and correctly use your information. However, neither people nor
                security systems are foolproof, including encryption systems. In
                addition, people can commit intentional crimes, make mistakes,
                or fail to follow policies. Therefore, while we use reasonable
                efforts to protect your personal information, we cannot
                guarantee its absolute security. If applicable law imposes any
                non-disclaimable duty to protect your personal information, you
                agree that intentional misconduct will be the standard used to
                measure our compliance with that duty.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">
                Can I update or correct my information?
              </h2>
              <p>
                The rights you have to request updates or corrections to the
                information Cynergy Studios collects depend on your relationship
                with Cynergy Studios. Personnel may update or correct their
                information as detailed in our internal company employment
                policies.
                <br />
                <br />
                Customers have the right to request the restriction of certain
                uses and disclosures of personally identifiable information as
                follows. You can contact us in order to (1) update or correct
                your personally identifiable information, (2) change your
                preferences with respect to communications and other information
                you receive from us, or (3) delete the personally identifiable
                information maintained about you on our systems (subject to the
                following paragraph), by canceling your account. Such updates,
                corrections, changes, and deletions will have no effect on other
                information that we maintain or information that we have
                provided to third parties in accordance with this Privacy Policy
                prior to such update, correction, change, or deletion. To
                protect your privacy and security, we may take reasonable steps
                (such as requesting a unique password) to verify your identity
                before granting you profile access or making corrections. You
                are responsible for maintaining the secrecy of your unique
                password and account information at all times.
                <br />
                <br />
                You should be aware that it is not technologically possible to
                remove each and every record of the information you have
                provided to us from our system. The need to back up our systems
                to protect information from inadvertent loss means that a copy
                of your information may exist in a non-erasable form that will
                be difficult or impossible for us to locate. Promptly after
                receiving your request, all personal information stored in
                databases we actively use, and other readily searchable media
                will be updated, corrected, changed, or deleted, as appropriate,
                as soon as and to the extent reasonably and technically
                practicable.
                <br />
                <br />
                If you are an end-user and wish to update, delete, or receive
                any information we have about you, you may do so by contacting
                the organization of which you are a customer.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">Personnel</h2>
              <p>
                If you are a Cynergy Studios worker or applicant, we collect
                information you voluntarily provide to us. We use the
                information collected for Human Resources purposes in order to
                administer benefits to workers and screen applicants.
                <br />
                <br />
                You may contact us in order to (1) update or correct your
                information, (2) change your preferences with respect to
                communications and other information you receive from us, or (3)
                receive a record of the information we have relating to you.
                Such updates, corrections, changes, and deletions will have no
                effect on other information that we maintain or information that
                we have provided to third parties in accordance with this
                Privacy Policy prior to such update, correction, change, or
                deletion.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">Sale of Business</h2>
              <p>
                We reserve the right to transfer information to a third party in
                the event of a sale, merger or other transfer of all or
                substantially all of the assets of Cynergy Studios or any of its
                Corporate Affiliates (as defined herein), or that portion of
                Cynergy Studios or any of its Corporate Affiliates to which the
                Service relates, or in the event that we discontinue our
                business or file a petition or have filed against us a petition
                in bankruptcy, reorganization or similar proceeding, provided
                that the third party agrees to adhere to the terms of this
                Privacy Policy.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">Affiliates</h2>
              <p>
                We may disclose information (including personal information)
                about you to our Corporate Affiliates. For page 6/8 purposes of
                this Privacy Policy, "Corporate Affiliate" means any person or
                entity that directly or indirectly controls, is controlled by,
                or is under common control with Cynergy Studios, whether by
                ownership or otherwise. Those Corporate Affiliates will treat
                any information relating to you that we provide to our Corporate
                Affiliates in accordance with the terms of this Privacy Policy.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">Governing Law</h2>
              <p>
                The laws of the United States govern this Privacy Policy without
                regard to its conflict of laws provision. You consent to the
                exclusive jurisdiction of the courts in connection with any
                action or dispute arising between the parties under or in
                connection with this Privacy Policy except for those individuals
                who may have rights to make claims under Privacy Shield or the
                Swiss-US framework.
                <br />
                <br />
                The laws of the United States, excluding its conflicts of law
                rules, shall govern this Agreement and your use of the website.
                Your use of the website may also be subject to other local,
                state, national, or international laws.
                <br />
                <br />
                By using Cynergy Studios or contacting us directly, you signify
                your acceptance of this Privacy Policy. If you do not agree to
                this Privacy Policy, you should not engage with our website, or
                use our services. Continued use of the website, direct
                engagement with us, or following the posting of changes to this
                Privacy Policy that do not significantly affect the use or
                disclosure of your personal information will mean that you
                accept those changes.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">Your Consent</h2>
              <p>
                We've updated our Privacy Policy to provide you with complete
                transparency into what is being set when you visit our site and
                how it's being used. By using Cynergy Studios, registering an
                account, or making a purchase, you hereby consent to our Privacy
                Policy and agree to its terms.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">Links to Other Websites</h2>
              <p>
                This Privacy Policy applies only to the Services. The Services
                may contain links to other websites not operated or controlled
                by Cynergy Studios. We are not responsible for the content,
                accuracy or opinions expressed in such websites, and such
                websites are not investigated, monitored or checked for accuracy
                or completeness by us. Please remember that when you use a link
                to go from the Services to another website, our Privacy Policy
                is no longer in effect. Your browsing and interaction on any
                other website, including those that have a link on our platform,
                is subject to that website’s own rules and policies. Such third
                parties may use their cookies or other methods to collect
                information about you.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">Cookies</h2>
              <p>
                Cynergy Studios uses "Cookies" to identify the areas of our
                website that you have visited. A cookie is a small piece of data
                stored on your computer or mobile device by your web browser. We
                use cookies to enhance the performance and functionality of our
                website, but are non-essential to their use. However, without
                these cookies, certain functionality, like videos, may become
                unavailable, or you would be required to enter your login
                details every time you visit the website, as we would not be
                able to remember that you had logged in previously. Most web
                browsers can be set to disable the use of Cookies. However, if
                you disable Cookies, you may not be able to access functionality
                on our website correctly or at all. We never place Personally
                Identifiable Information in Cookies.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">
                Blocking and disabling cookies and similar technologies
              </h2>
              <p>
                Wherever you're located, you may also set your browser to block
                cookies and similar technologies. Still, this action may block
                our essential cookies and prevent our website from functioning
                properly, and you may not be able to utilize all of its features
                and services fully. You should also be aware that you may also
                lose some saved information (e.g., saved login details and site
                preferences) if you block cookies on your browser. Different
                browsers make different controls available to you. Disabling a
                cookie or category of cookie does not delete the cookie from
                your browser, and you will need to do this yourself from within
                your browser. You should visit your browser's help menu for more
                information.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">Changes To Our Privacy Policy</h2>
              <p>
                We may change our Service and policies, and we may need to make
                changes to this Privacy Policy so that they accurately reflect
                our Service and policies. Unless otherwise required by law, we
                will notify you (for example, through our Service) before we
                make changes to this Privacy Policy and give you an opportunity
                to review them before they go into effect. Then, if you continue
                to use the Service, you will be bound by the updated Privacy
                Policy. If you do not want to agree to this or any updated
                Privacy Policy, you can delete your account.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">Third-Party Services</h2>
              <p>
                We may display, include, or make available third-party content
                (including data, information, applications, and other products
                and services) or provide links to third-party websites or
                services ("Third-Party Services").
                <br />
                <br />
                You acknowledge and agree that Cynergy Studios shall not be
                responsible for any Third-Party Services, including their
                accuracy, completeness, timeliness, validity, copyright
                compliance, legality, decency, quality, or any other aspect
                thereof. Cynergy Studios does not assume and shall not have any
                liability or responsibility to you or any other person or entity
                for any Third-Party Services.
                <br />
                <br />
                Third-party services and links thereto are provided solely as a
                convenience to you and you access and use them entirely at your
                own risk and subject to such third parties' terms and
                conditions.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">Facebook Pixel</h2>
              <p>
                Facebook pixel is an analytics tool that allows you to measure
                the effectiveness of your advertising by page 8/8, understanding
                the actions people take on your website/app. You can use the
                pixel to: Make sure your ads are shown to the right people.
                Facebook Pixel may collect information from your device when you
                use the service. Facebook Pixel collects information that is
                held in accordance with its Privacy Policy.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">Google Analytics</h2>
              <p>
                Google Analytics 4 is an analytics tool that collects both
                website and app data to understand the customer journey better.
                It is used to measure the effectiveness of advertising campaigns
                and identify the actions users take on website/app. GA4 includes
                privacy controls such as cookieless measurement, and behavioral
                and key event modeling. Google Analytics 4 may collect
                information from your device when you use the service. Google
                Analytics 4 collects information that is held in accordance with
                its Privacy Policy.
              </p>
            </div>
          </div>
          <div className="row mt-5">
            <div className="col-md-12">
              <h2 className="mb-4 fw-bold">Tracking Technologies</h2>
              <ul>
                <li>Local Storage</li>
              </ul>
              <p>
                Local Storage, sometimes known as DOM storage, provides web apps
                with methods and protocols for storing client-side data. Web
                storage supports persistent data storage, similar to cookies,
                but with a greatly enhanced capacity and no information stored
                in the HTTP request header.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="mt-5">
        <InnerCta />
      </div>
      <Footer />
    </>
  );
};

export default page;
