export const cardData = [
    {heading:"OrderPay: Mobile Ordering",showFull:true,tags:["#softwaredevelopment","#strategy","#designservices"],description:" Take more tips, drive higher spend and turn tables faster, with the UK’s most cost-effective order and payment provider.We don’t believe in one-size-fits-all technology. Whether you’re a national restaurant chain, an independent cafe or an 18-hole golf course, we’ll help you find the right solution for your business.Let your customers order and pay the way that suits them, with no need to download an app or wait for a card terminal.",imageUrl:"/images/achievement-page/orderPaying.png"},
    {heading:"Cooper's Hawk",tags:["#softwaredevelopment","#strategy","#designservices"],description:"We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",imageUrl:"/images/achievement-page/image-4.png"},
    {heading:"KC Elite ecommerce store",tags:["#softwaredevelopment","#strategy"],description:"We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",imageUrl:"/images/achievement-page/kcElite.png"},
    {heading:"App Store Preview",tags:["#softwaredevelopment","#designservices"],description:"We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",imageUrl:"/images/achievement-page/appStore.png"},
    {heading:"Disfruta",tags:["#strategy","#designservices"],description:"We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",imageUrl:"/images/achievement-page/image-5.png"},
    {heading:"Pauseitive",tags:["#softwaredevelopment","#designservices"],description:"We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",imageUrl:"/images/achievement-page/image-6.png"},
    {heading:"Ontapp",tags:["#strategy","#designservices"],description:"We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",imageUrl:"/images/achievement-page/image-7.png"},
    {heading:"PHILApp: Unity With a Purpose ",tags:["#softwaredevelopment","#designservices"],description:"We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",imageUrl:"/images/achievement-page/image-8.png"},
    {heading:"Cooper's Hawk",tags:["#strategy","#designservices"],description:"We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",imageUrl:"/images/achievement-page/image-9.png"}
]             